spring:
  data:
    elasticsearch:
      cluster-name: es-server6.3-test
      cluster-nodes: 192.168.21.25:9200
      repositories:
        enabled: true
jufan:
  threadpool:
    batchpool:
      threadNamePrefix: batchpool-
      corePoolSize: 10
      maxPoolSize: 10
      keepAliveSeconds: 180
      queueCapacity: 1000