language: java
sudo: required
services:
- docker

jdk:
- oraclejdk8

install:
- mvn clean install -B -V -Pall

script:
- docker ps -a
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push huifumanlove/springboot-simple

after_success:
- mvn clean cobertura:cobertura coveralls:report -Pall