#路由规则
zuul:
  routes:
    b-service:
      path: /service/**
      serviceId: b-service
      sensitiveHeaders: ''
    c-aggregator:
      path: /aggregator/**
      serviceId: c-aggregator
      sensitiveHeaders: ''
    d-app:
      path: /app/**
      serviceId: d-app
      sensitiveHeaders: ''