# eureka注册拉取配置
eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
# oauth2安全配置
security:
  oauth2:
    client:
      client-id: service_id
      client-secret: service_secret
      grant-type: client_credentials
      access-token-uri: http://${creed.uaa.domain}:${creed.uaa.port}/oauth/token
    resource:
      token-info-uri: http://${creed.uaa.domain}:${creed.uaa.port}/oauth/check_token