mybatis-plus:
  global-config:
    #xml调试,无需重启
    refresh: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.22:3306/jufan_crawler?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: We-are-hero-2015
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      read-only: false
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 192.168.21.27
    port: 6379
    database: 0
    password: We-are-hero-2015
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
jetcache:
  statIntervalMinutes: 1
  hidePackages: com.geercode.creed.samples
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
      limit: 100
      expireAfterWriteInMillis: 30000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      expireAfterWriteInMillis: 100000
      uri: redis://We-are-hero-2015@192.168.21.27?database=0
      keyPrefix: 'springboot-multi-web:'

