# eureka注册拉取配置
eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
# oauth2安全配置
security:
  oauth2:
    client:
      client-id: app_id
      client-secret: app_secret
      grant-type: client_credentials
      access-token-uri: http://${creed.uaa.domain}:${creed.uaa.port}/oauth/token
# feign配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request: true
    response: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 90000
        loggerLevel: basic
# ribbon配置
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  eager-load:
    enabled: true
# hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE