apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8500
---
apiVersion: v1
kind: Endpoints
metadata:
  name: consul
subsets:
  - addresses:
      - ip: 172.18.0.8
    ports:
      - port: 8500