apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8848
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nacos
subsets:
  - addresses:
      - ip: 172.18.0.7
    ports:
      - port: 8848