apiVersion: v1
kind: Service
metadata:
  name: sentinel
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sentinel
subsets:
  - addresses:
      - ip: 192.168.1.119
    ports:
      - port: 8080