apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2181
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zookeeper
subsets:
  - addresses:
      - ip: 172.18.0.6
    ports:
      - port: 2181