management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  zipkin:
    base-url: http://192.168.21.28:9411/
  sleuth:
    sampler:
      probability: 1
dubbo:
  registry:
    address: 'zookeeper://t.jufandev.com:21823'
  protocol:
    name: dubbo
    port: 12345
  provider:
    filter: tracing
  consumer:
    filter: tracing