management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
spring:
  zipkin:
    base-url: http://192.168.21.28:9411/
  sleuth:
    sampler:
      probability: 1
    web:
      skip-pattern: ${server.servlet.context-path:}/actuator.*
dubbo:
  application:
    name: svc-consul-service
  registry:
    address: 'zookeeper://t.jufandev.com:21823'
  protocol:
    name: dubbo
    port: 12345
  provider:
    filter: tracing
  consumer:
    filter: tracing