version: "3"

services:
  nacos:
    image: nacos/nacos-server:1.0.0
    container_name: nacos
    dns:
      - 119.29.29.29
      - 114.114.114.114
    networks:
      default:
        ipv4_address: 172.18.0.7
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - /opt/nacos/init.d:/home/nacos/init.d
      - /opt/nacos/conf:/home/nacos/conf
      - /opt/nacos/data:/home/nacos/data
      - /opt/nacos/logs:/home/nacos/logs
networks:
  default:
    external:
      name: middleware-network